version: '3'
services:
  postgres:
    image: postgres:latest
    ports:
    - 5432:5432
    environment:
      POSTGRES_DB: "flan"
      POSTGRES_USER: "flanuser"
      POSTGRES_PASSWORD: "flanpass"
