version: '3'
services:
  web:
    build: .
    ports:
    - 8000:8000
    links:
    - db
#    Environment:
 #   - HOSTNAME: 'flanvid1'
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "flan"
      POSTGRES_USER: "flanuser"
      POSTGRES_PASSWORD: "flanpass"
