# Generated by Django 2.1 on 2018-08-28 21:58

from django.db import migrations
import videos.models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_remove_video_vid_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=videos.models.YouTubeURL(max_length=200),
        ),
    ]
