# Generated by Django 2.1 on 2018-08-29 12:52

from django.db import migrations
import videos.models
import videos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20180828_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=videos.models.YouTubeID(max_length=200, validators=[videos.validators.validate_yt_id]),
        ),
    ]
