# Generated by Django 2.1 on 2018-08-29 12:58

from django.db import migrations
import videos.models
import videos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_auto_20180829_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='vid_id',
            field=videos.models.YouTubeID(max_length=200, unique=True, validators=[videos.validators.validate_yt_id]),
        ),
    ]
