# Generated by Django 2.1 on 2018-08-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_auto_20180829_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='channel',
            field=models.CharField(default='Banan', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='thumb_url',
            field=models.CharField(default='Korv', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(default='katt', max_length=500),
            preserve_default=False,
        ),
    ]
