# Generated by Django 2.1 on 2018-08-29 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_auto_20180829_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='channel',
        ),
    ]
