# Generated by Django 2.1 on 2018-09-02 14:12

from django.db import migrations
import videos.models
import videos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_video_curr_playing'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='vid_url',
            field=videos.models.YouTubeURL(default='svt.se', max_length=200, unique=True, validators=[videos.validators.validate_yt_url]),
            preserve_default=False,
        ),
    ]
